
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AMPERS AND ARRAY AT BEGIN BOOLAND BOOLOR BREAK CASE CLASS COLON COMMA COMMENT DEF DIVIDE DOLLARSGN DOT DUODOT ELSE ELSIF END ENSURE EQCOMP EQUALS EXPON FALSE FLOAT FOR GREATEQTH GREATH ID IF IN INT LBRACE LBRAKET LESSEQTH LESSTH LPAREN MINUS MINUSEQ MODULE NEXT NIL OR PIPE PLUS PLUSEQ RBRACE RBRAKET RETRY RETURN RPAREN SELF SEMICOLON STRING SUPER THEN TILDE TIMES TRIDOT TRUE UNDERSCR UNLESS UNTIL WHEN WHILEnumeric : INTnumeric : FLOATaddition : numeric PLUS numericsubstrac : numeric MINUS numeric'
    
_lr_action_items = {'INT':([0,],[2,]),'FLOAT':([0,],[3,]),'$end':([1,2,3,],[0,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'numeric':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> numeric","S'",1,None,None,None),
  ('numeric -> INT','numeric',1,'p_numeric_int','semtic.py',14),
  ('numeric -> FLOAT','numeric',1,'p_numeric_float','semtic.py',18),
  ('addition -> numeric PLUS numeric','addition',3,'p_addition','semtic.py',22),
  ('substrac -> numeric MINUS numeric','substrac',3,'p_substrac','semtic.py',26),
]
